---
- hosts: all
  gather_facts: false
  tasks: 

    - name: delete the deployment and services if any
      shell: "kubectl delete -f '/tmp/configurations/{{ depl_name }}.yaml' -n '{{k3s_name_space}}'"
      ignore_errors: yes

    - name: removing yaml deployment file
      shell: sudo rm -rf '/tmp/configurations/{{ depl_name }}.yaml'

    - name: Check if /tmp/configurations is empty
      ansible.builtin.find:
        paths: /tmp/configurations
        patterns: "*"
      register: find_result

    - name: Delete /tmp/configurations if it's empty
      ansible.builtin.file:
        path: /tmp/configurations
        state: absent
      when: find_result.matched == 0

    # - name: delete deployment
    #   shell: "kubectl delete deployment '{{depl_name}}' -n '{{k3s_name_space}}'"

    # - name: delete service 
    #   shell: "kubectl delete svc '{{svc_name}}' -n '{{k3s_name_space}}'"
    #   ignore_errors: yes

    - name : delete custom created namespace
      shell: "kubectl delete namespace '{{k3s_name_space}}'"
      when: k3s_name_space != "default"