---
- hosts: all
  gather_facts: false

  tasks:
    # - name: Enable the required container features- cgroups
    #   command: "sudo sed -i '$ s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' /boot/cmdline.txt"

    - name: download k3s agent on worker node & join it to k3s cluster
      shell: "curl -sfL https://get.k3s.io | K3S_URL={{ apiserver_url }} K3S_TOKEN={{ k3s_worker_token }} sh - "